version: '3.8'

services:
  libcam:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mredig/libcamera-example:latest
    restart: unless-stopped
    privileged: true
    # cap_add:
    #   - ALL
    # devices:
    #   - /dev/video0:/dev/video0
      # - /dev/video10:/dev/video10
      # - /dev/video11:/dev/video11
      # - /dev/video12:/dev/video12
      # - /dev/video13:/dev/video13
      # - /dev/video14:/dev/video14
      # - /dev/video15:/dev/video15
      # - /dev/video16:/dev/video16
      # - /dev/video18:/dev/video18
      # - /dev/video19:/dev/video19
      # - /dev/video20:/dev/video20
      # - /dev/video21:/dev/video21
      # - /dev/video22:/dev/video22
      # - /dev/video23:/dev/video23
      # - /dev/video31:/dev/video31
      # - /dev/media0:/dev/media0
      # - /dev/media1:/dev/media1
      # - /dev/v4l-subdev0:/dev/v4l-subdev0
    volumes:
      # - /dev/v4l/:/dev/v4l/
      - /run/udev/:/run/udev:ro
    # group_add:
    #   - video
